spring.application.name=auth-service
server.port=8081

spring.data.mongodb.uri=${MONGO_URI:mongodb://localhost:27017/EcommerceDB}

jwt.secret=${JWT_SECRET:r8JvP3zQ2Lm9XcT5sA7WkD4uHn6FqB1yYp0eZVgRjCw8MUtN}
jwt.expiration=86400000

cart.service.url=${CART_SERVICE_URL:http://localhost:8083}

# Automatically include validation messages in the default /error response
server.error.include-message=always
server.error.include-binding-errors=always
